name: deploy_go

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      role_arn:
        required: true
        type: string
      target_type:
        required: true
        type: string
      target_name:
        required: true
        type: string
      regions:
        required: true
        type: string
      arch:
        required: true
        type: string
    secrets:
      github_login:
        required: true

jobs:
  build:
    runs-on: [self-hosted, "${{ inputs.arch }}"]
    name: "[${{ inputs.target_type }}][${{ inputs.target_name }}] build"
    steps:
      - uses: actions/checkout@v3
      - run: echo here ${{ vars.AWS_ACCOUNT_ID_STG }}
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ inputs.role_arn }}
          aws-region: us-east-1
      - uses: docker/setup-buildx-action@v2
      - run: >
          ./.github/scripts/build.sh ${{ inputs.env }} ${{ inputs.target_type }} ${{ inputs.target_name }} '${{ inputs.regions }}' ${{ inputs.arch }} ${{ secrets.github_login }}

  wait:
    runs-on: self-hosted
    name: "[${{ inputs.target_type }}][${{ inputs.target_name }}] wait"
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        region: ${{ fromJson(inputs.regions) }}
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ inputs.role_arn }}
          aws-region: us-east-1
      - run: >
          ./.github/scripts/wait.sh ${{ inputs.env }} ${{ inputs.target_type }} ${{ inputs.target_name }} ${{ matrix.region }} ${{ inputs.arch }} ${{ secrets.github_login }}
