name: deploy_go

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      aws_account_id:
        required: true
        type: string
      role_arn:
        required: true
        type: string
      target_type:
        required: true
        type: string
      target_name:
        required: true
        type: string
      regions:
        required: true
        type: string
      all_regions:
        required: true
        type: string
      os:
        required: true
        type: string
      arch:
        required: true
        type: string
      runs_on:
        required: true
        type: string
      dry_run:
        required: false
        default: false
        type: boolean
    # secrets:
    #   MY_GITHUB_LOGIN:
    #     required: true

jobs:
  build:
    runs-on: ${{ inputs.runs_on }}
    name: "[${{ inputs.target_type }}][${{ inputs.target_name }}] build"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: f-lib/ga-workflows
          path: cur_repo_root
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role_arn }}
          aws-region: us-east-1
      - uses: docker/setup-buildx-action@v3
      - run: >
          ${GITHUB_WORKSPACE}/cur_repo_root/.github/scripts/build.sh ${{ inputs.env }} ${{ inputs.target_type }} ${{ inputs.target_name }} '${{ inputs.regions }}' ${{ inputs.os }} ${{ inputs.arch }} ${{ secrets.MY_GITHUB_LOGIN }} ${{ inputs.aws_account_id }} ${{ inputs.dry_run }} ${{ github.event.repository.name }} '${{ inputs.all_regions }}'
      - run: >
          ${GITHUB_WORKSPACE}/cur_repo_root/.github/scripts/test.sh ${{ inputs.env }} ${{ inputs.target_type }} ${{ inputs.target_name }} '${{ inputs.regions }}' ${{ inputs.os }} ${{ inputs.arch }} ${{ secrets.MY_GITHUB_LOGIN }} ${{ inputs.aws_account_id }} ${{ inputs.dry_run }} ${{ github.event.repository.name }} '${{ inputs.all_regions }}'

  wait:
    runs-on: ubuntu-latest
    name: "[${{ inputs.target_type }}][${{ inputs.target_name }}] wait"
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        region: ${{ fromJson(inputs.regions) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: f-lib/ga-workflows
          path: cur_repo_root
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role_arn }}
          aws-region: us-east-1
      - run: >
          ${GITHUB_WORKSPACE}/cur_repo_root/./.github/scripts/wait.sh ${{ inputs.env }} ${{ inputs.target_type }} ${{ inputs.target_name }} ${{ matrix.region }} ${{ inputs.dry_run }} ${{ github.event.repository.name }}

