name: deploy_go_all

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      aws_account_id:
        required: true
        type: string
      role_arn:
        required: true
        type: string
      regions:
        required: true
        type: string
      config:
        required: true
        type: string
      dry_run:
        required: false
        default: false
        type: boolean
      notify_fail:
        required: false
        default: false
        type: boolean
      slack_channel:
        required: false
        type: string
    secrets:
      github_login:
        required: true
      slack_token:
        required: false

jobs:
  deploy_go:
    name: deploy-go
    uses: ./.github/workflows/deploy_go_single.yml
    with:
      env: ${{ inputs.env }}
      aws_account_id: ${{ inputs.aws_account_id }}
      role_arn: ${{ inputs.role_arn }}
      target_type: ${{ matrix.config.type }}
      target_name: ${{ matrix.config.name }}
      regions: ${{ matrix.config.regions == 'all' && inputs.regions || matrix.config.regions }}
      arch: ${{ matrix.config.arch }}
      dry_run: ${{ inputs.dry_run }}
    secrets:
      github_login: ${{ secrets.github_login }}
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(inputs.config) }}

  notify_fail:
    runs-on: self-hosted
    needs: [deploy_go]
    if: ${{ inputs.notify_fail && failure() }}
    steps:
      - run: echo "${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
      - uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ inputs.slack_channel }}
          payload: |
            {
              "text": "Workflow failed! ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack_token }}
