name: deploy_go_all

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      path:
        required: true
        type: string
      aws_account_id:
        required: true
        type: string
      dry_run:
        required: false
        default: false
        type: boolean

jobs:
  deploy_go:
    name: deploy-go
    uses: ./.github/workflows/deploy_go_single.yml
    needs: [get_params]
    with:
      env: ${{ inputs.env }}
      aws_account_id: ${{ inputs.aws_account_id }}
      role_arn: arn:aws:iam::${{ inputs.aws_account_id }}:role/flicspy-${{ github.event.repository.name }}-github-actions-deploy
      target_type: ${{ matrix.config.type }}
      target_name: ${{ matrix.config.name }}
      regions: ${{ matrix.config.regions == 'all' && needs.get_params.outputs.target_regions || matrix.config.regions }}
      arch: ${{ matrix.config.arch }}
      dry_run: ${{ inputs.dry_run }}
    secrets:
      github_login: ${{ vars.MY_GITHUB_LOGIN }}
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.get_params.outputs.config) }}

  notify:
    runs-on: self-hosted
    needs: [deploy_go]
    if: ${{ success() || failure() }}
    steps:
      - uses: slackapi/slack-github-action@v1.24.0
        if: ${{ needs.deploy_go.result == 'success' }}
        name: notify success
        with:
          channel-id: "github-workflow"
          payload: |
            {
              "text": ":green_heart: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
      - uses: slackapi/slack-github-action@v1.24.0
        if: ${{ needs.deploy_go.result == 'failure' }}
        name: notify failure
        with:
          channel-id: "github-workflow"
          payload: |
            {
              "text": "<!here> :broken_heart: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}

  get_params:
    runs-on: self-hosted
    name: get_params
    steps:
      - uses: actions/checkout@v3
      - id: load_json
        uses: f-lib/github-actions/read-file@main
        with:
          path: ${{ inputs.path }}
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/flicspy-${{ github.event.repository.name }}-github-actions-deploy
          aws-region: us-east-1
      - id: get_target_regions
        uses: f-lib/github-actions/get-target-regions@main
        with:
          ssm_param_name: flicspy-${{ inputs.env }}-${{ github.event.repository.name }}-blue-green-regions
          ssm_param_region: us-east-2
    outputs:
      target_regions: ${{ steps.get_target_regions.outputs.target_regions }}
      config: ${{ steps.load_json.outputs.text }}
