name: deploy_go_all

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      path:
        required: true
        type: string
      aws_account_id:
        required: true
        type: string
      dry_run:
        required: false
        default: false
        type: boolean

jobs:
  deploy_go:
    name: ">"
    uses: ./.github/workflows/deploy_go_single.yml
    needs: [get_params]
    with:
      env: ${{ inputs.env }}
      aws_account_id: ${{ inputs.aws_account_id }}
      role_arn: arn:aws:iam::${{ inputs.aws_account_id }}:role/flicspy-${{ github.event.repository.name }}-github-actions-deploy
      target_type: ${{ matrix.config.type }}
      target_name: ${{ matrix.config.name }}
      regions: ${{ matrix.config.regions == 'all' && needs.get_params.outputs.target_regions || matrix.config.regions }}
      arch: ${{ matrix.config.arch }}
      dry_run: ${{ inputs.dry_run }}
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.get_params.outputs.config) }}

  notify_success:
    needs: [deploy_go]
    if: ${{ success() }}
    uses: ./.github/workflows/notify_slack.yml
    with:
      channel: github-workflow
      message: >-
        ${{ inputs.env == 'prd' && ':large_green_circle:' || ':green_heart:' }}
    secrets: inherit

  notify_failure:
    needs: [deploy_go]
    if: ${{ failure() }}
    uses: ./.github/workflows/notify_slack.yml
    with:
      channel: github-workflow
      message: >-
        <!here>\n${{ inputs.env == 'prd' && ':red_circle:' || ':broken_heart:' }}
    secrets: inherit

  # notify_success:
  #   runs-on: ubuntu-latest
  #   needs: [deploy_go]
  #   if: ${{ success() }}
  #   steps:
  #     - uses: slackapi/slack-github-action@v1.24.0
  #       with:
  #         channel-id: "github-workflow"
  #         payload: |
  #           {
  #             "text": ":green_heart: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
  #           }
  #       env:
  #         SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}

  # notify_failure:
  #   runs-on: ubuntu-latest
  #   needs: [deploy_go]
  #   if: ${{ failure() }}
  #   steps:
  #     - uses: slackapi/slack-github-action@v1.24.0
  #       name: notify failure
  #       with:
  #         channel-id: "github-workflow"
  #         payload: |
  #           {
  #             "text": "<!here>\n:broken_heart: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
  #           }
  #       env:
  #         SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}

  get_params:
    runs-on: ubuntu-latest
    name: get_params
    steps:
      - uses: actions/checkout@v3
      - id: load_json
        uses: f-lib/github-actions/read-file@main
        with:
          path: ${{ inputs.path }}
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/flicspy-${{ github.event.repository.name }}-github-actions-deploy
          aws-region: us-east-1
      - id: get_target_regions
        uses: f-lib/github-actions/get-target-regions@main
        with:
          ssm_param_name: flicspy-${{ inputs.env }}-${{ github.event.repository.name }}-blue-green-regions
          ssm_param_region: us-east-2
    outputs:
      target_regions: ${{ steps.get_target_regions.outputs.target_regions }}
      config: ${{ steps.load_json.outputs.text }}
