name: notify_slack

on:
  workflow_call:
    inputs:
      channel:
        required: true
        type: string
      message:
        required: true
        type: string
    # secrets:
    #   SLACK_TOKEN:
    #     required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ inputs.channel }}
          payload: |
            {
              "text": "${{ inputs.message }} ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}